### ISSUE TITLE
Few things -

### ISSUE THREAD

**Issue by SicoZ** [Doc94/TS3IconManager#10]
Dear Doc94,
- Hello i want to ask about few things that can i do with IconManager or not ,
  first thing when user connect to my website bot ask him for the unique id so can i change that to make the bot use like the ip of the user so he didn't need to insert the unique id ?!

anther thing i want to arrange the checkboxs in two columns instead of
one single long column like the photo in the "Attach Files" ?!

i know i ask to much but if you really can help me with that i really need this things,

Thanks "Sorry for bad English" ..
![ji9tqzj](https://cloud.githubusercontent.com/assets/14951779/10262321/c2191302-69c3-11e5-8a5f-bc0b9d2611ce.png)

**Comment by Dramex** [comment]
the photo attached done by me :)
you can do as the photo with simple html & css 
its not related to the programming, its related for the design :)

**Comment by SicoZ** [comment]
i'm not that good at HTML & CSS so if you can help me with that like giving me an example or tutorial,
if you have a teamspeak to contact you with !

**Comment by Doc94** [comment]
Hello.
About your comments ...
One-could arm that does not require uuid (at least that do not ask the user)
but I work with online users because to get the ip ts should I take complete list of members, the other is asking uuid but also add IP verification that internal serious and that removing verification code but it took me areglar and test time.

2- On the design of columns ... I try to start this little project but struggled to fit the data because the list is generated as the system returns the groups that assign ABLE or not ...

Try to work on them but results would at one time more .. (quisas in the field of "dev" of this project have updates of these things ...

**Comment by SicoZ** [comment]
Hello.

i understand what you say, but the reason that make me post that comments that i found a lot of teamspeak 3 server using the IP to active the user in teamspeak this days so the function is not impassable it's just need to update your script that all so if you have the plane to update it can you tell us when you will release the next update ?!

thanks ,

**Comment by Doc94** [comment]
Well, since this information when you can (as I have study subjects) will try to remove the system UUID and use IP.He is coming out to take advantage of optimizing algunsa functions.
An update to date by perhaps a test version in 2 or 1 week.

**Comment by warningman** [comment]
Thanks Doc94 this will help us to mach

**Comment by warningman** [comment]
and the java script if he off it in browser he will can take all games and thanks

**Comment by Doc94** [comment]
On the subject of js in the section I have a solution to that problem where the system recounts the selected icons and compares the maximum ...
because it is in dev and could prove even by topic of time.

**Comment by Doc94** [comment]
I just realized that using ip involves an error if more than one user session so as a first devupdate only support, the future system based on ip let the user choose to use.
Quisas today or tomorrow have a updatedev.

**Comment by TATO-1** [comment]
Is there any auto way I mean if the client click activate. 

The bot automatically active the client

**Comment by TATO-1** [comment]
And please help with my problem

---

http://prntscr.com/8py617

Warning: include(./lang/ES.php): failed to open stream: No such file or directory in /home/foxgamers/public_html/lang/loadlang.php on line 10

Warning: include(): Failed opening './lang/ES.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/foxgamers/public_html/lang/loadlang.php on line 10

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/foxgamers/public_html/procesar.php:17) in /home/foxgamers/public_html/modulos/listador.php on line 11

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/foxgamers/public_html/procesar.php:17) in /home/foxgamers/public_html/modulos/listador.php on line 11
