### ISSUE TITLE
uid problem

### ISSUE THREAD

**Issue by TATO-1** [Doc94/TS3IconManager#11]
hi 
Doc94, 

i have problem after i put uid 

http://prntscr.com/8py617

Warning: include(./lang/ES.php): failed to open stream: No such file or directory in /home/foxgamers/public_html/lang/loadlang.php on line 10

Warning: include(): Failed opening './lang/ES.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/foxgamers/public_html/lang/loadlang.php on line 10

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/foxgamers/public_html/procesar.php:17) in /home/foxgamers/public_html/modulos/listador.php on line 11

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/foxgamers/public_html/procesar.php:17) in /home/foxgamers/public_html/modulos/listador.php on line 11

**Comment by Doc94** [comment]
Sorry for the time..

Try change the name file in directory /lang (es.php to ES.php) i updating this when upload the dev version for IP...

**Comment by TATO-1** [comment]
Thanks it's work

But I see some server have the same script but they have automatic script

What I mean is whene I open the website script he just give me the icon without his or any ip's or any thing 

Plz how does that work
