### ISSUE TITLE
Code mistmatch even if correct?

### ISSUE THREAD

**Issue by Foggy-J** [Doc94/TS3IconManager#13]
Hi,

I've had previous issues however they have all been sorted. My final 2 issues are that the code is always incorrect when it isn't and also the icons don't show up on the website.

TheKingFoggy

**Comment by thekingfoggy** [comment]
I fixed all the previous errors, however I have one more issue.
![capture](https://cloud.githubusercontent.com/assets/16501241/12066210/0add4118-afdc-11e5-8c86-e6c81e46ad17.PNG)
