### ISSUE TITLE
how to display icons?

### ISSUE THREAD

**Issue by iiONE** [Doc94/TS3IconManager#14]
hello man 
can you please hep me with TS3 ICON MANGER 
i don't know how to put icons in geticonos.php
if you can help me or make a video tutorial it will be awesome﻿

**Comment by Foggy-J** [comment]
if you are running it on a 'WampServer' like I am, just go to the homepage of the icon manager website, the go and type after your homepage '/iconos/geticonos.php', then it should load all the icons
