### ISSUE TITLE
invalid URI supplied

### ISSUE THREAD

**Issue by akonopcz** [Doc94/TS3IconManager#19]
Hello when im adding UID and proceed to the next site i get this ?

ERROR: [DEBUG] 
[DEBUG] : invalid URI supplied
[DEBUG] 0

what i shoud do?

**Comment by Doc94** [comment]
Well this code its so broken.. (Abandoned)
You can check the framework what use the script to check this error.
http://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework
