### ISSUE TITLE
Add confirmation to script

### ISSUE THREAD

**Issue by Doc94** [Doc94/TS3IconManager#2]
Try riding a basic system to send a PM via ts with a confirmation code to assign ranges.

Possible modifications:
-Use MYSQL as log
-Use PHP code to generate a unique and temporary confirmation (only one session ..)

**Comment by DmACKGL** [comment]
O que al usuario le envíe un Poke con un link de confirmación (?)

**Comment by Doc94** [comment]
Es que de ese metodo tendria que dejar un registro extra usando MYSQL y dejarlo en espera y si nunca responden el sistema tendra muchos pendientes..
En cambio si uso PHP para generar un codigo que quede por sesion y se envie por PM/Poke solo tendra que ingresarlo en el listardor.php para que el iconizador.php compruebe y proceda como corresponde.

**Comment by DmACKGL** [comment]
Pero que sea un código temporal que dure 5 minutos y si no responde se cancela y se elimina

**Comment by Doc94** [comment]
El codigo durara lo que el usuario tenga la pestaña donde ejecuta el modulo de listador....
Si la cierra pierde el codigo... El codigo se enviara via POKE al ejecutar el listador y debera ingresarlo ahi antes de dar a guardar...
o para ahorrar consultas query podria generarlo antes del listador cose que pida el codigo antes de listar... aunque tendria que jugar con if y jquery para no perder variables en el proceso...

Intentare lo segundo que dije en la tarde o mañana... haber que sale sin arruinar lo que ya esta armado...

**Comment by DmACKGL** [comment]
Por mientras estoy terminando de instalar el GitLab
