### ISSUE TITLE
Any idea how to display icons?

### ISSUE THREAD

**Issue by konradmm** [Doc94/TS3IconManager#4]
Have no idea what these icon images are from and how do i import them.
Cant do it manually... got too many

**Comment by konradmm** [comment]
nvm, found out geticonos.php xD

**Comment by DmACKGL** [comment]
No it's possible, because you need access to the server files and export them

**Comment by Doc94** [comment]
Fix the file geticonos.php
Due to an error in the directories include it.
You must download the "icons" and "modules / listador.php"
