### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Akabr** [Doc94/TS3IconManager#7]
????Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at C:\AppServ\www\ts\iconizar.php:16) in C:\AppServ\www\ts\modulos\iconizador.php on line 11

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at C:\AppServ\www\ts\iconizar.php:16) in C:\AppServ\www\ts\modulos\iconizador.php on line 11
[DEBUG] An unexpected error has occurred 
[DEBUG] Error message: invalid clientID
[DEBUG] The error code is 512
The UUID entered is invalid or not currently connected to ts3??

**Comment by Doc94** [comment]
what values you input in the script?

**Comment by Akabr** [comment]
Hello and sorry for late 

but i dont understand what you mean with values we put in the script

and By the way the server is Windows 2012

**Comment by Doc94** [comment]
Values you enter the system? ...
Since the code at least to me and many people do not give them that mistake ..
Check that you have properly configured your php.ini and whether the system supports the use of meetings ... which is where this causing problems ..

**Comment by Akabr** [comment]
Hello i try the script with other linux server and its ok 
but when i try it in windows doesnt work 
and i want to use it in windows server 2012

**Comment by Doc94** [comment]
Well, remember in Windows server the services  Web, like PHP, need special permisions in the host s.o (check your internal service of your s.o, and your firewall (yep the firewall of Windows Server R2)) and RE Check your trigger ports, and if you have  a clean instalation check the stocks services of Windows
